name: online_course
description: Online Course App.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_custom_tab_bar: ^1.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/categories/